GET https://bapbmjvn4l.execute-api.us-west-1.amazonaws.com/prod/spaces
### 
POST https://bapbmjvn4l.execute-api.us-west-1.amazonaws.com/prod/spaces
content-type: application/json

  {
    "location":"Paris"
  }
###
GET https://bapbmjvn4l.execute-api.us-west-1.amazonaws.com/prod/spaces?id=34
###

###
DELETE https://bapbmjvn4l.execute-api.us-west-1.amazonaws.com/prod/spaces?id=34
###

###
PUT https://bapbmjvn4l.execute-api.us-west-1.amazonaws.com/prod/spaces?id=34
content-type: application/json

  {
    "location":"Rome"
  }